// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

// A tactical alert raised by a detector.
type Alert struct {
	// Inputs that contributed to the alert, by name.
	Features AlertFeatures `json:"features"`

	// ID corresponds to the JSON schema field "id".
	ID string `json:"id"`

	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS MatchClockSeconds `json:"match_clock_s"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID MatchID `json:"match_id"`

	// Message corresponds to the JSON schema field "message".
	Message string `json:"message"`

	// Offset of the event that triggered the alert.
	Offset Offset `json:"offset"`

	// Period corresponds to the JSON schema field "period".
	Period Period `json:"period"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`

	// TeamID corresponds to the JSON schema field "team_id".
	TeamID int `json:"team_id"`

	// Threshold corresponds to the JSON schema field "threshold".
	Threshold float64 `json:"threshold"`

	// Type corresponds to the JSON schema field "type".
	Type AlertType `json:"type"`

	// Detector output (e.g. z-score or heuristic goal score).
	Value float64 `json:"value"`

	// WindowS corresponds to the JSON schema field "window_s".
	WindowS int `json:"window_s"`
}

// Inputs that contributed to the alert, by name.
type AlertFeatures map[string]float64

type AlertType string

const AlertTypeControlShift AlertType = "control_shift"
const AlertTypeGoalThreat AlertType = "goal_threat"
const AlertTypeMomentumShift AlertType = "momentum_shift"

var enumValues_AlertType = []interface{}{
	"momentum_shift",
	"goal_threat",
	"control_shift",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AlertType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AlertType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AlertType, v)
	}
	*j = AlertType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Alert) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["features"]; raw != nil && !ok {
		return fmt.Errorf("field features in Alert: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Alert: required")
	}
	if _, ok := raw["match_clock_s"]; raw != nil && !ok {
		return fmt.Errorf("field match_clock_s in Alert: required")
	}
	if _, ok := raw["match_id"]; raw != nil && !ok {
		return fmt.Errorf("field match_id in Alert: required")
	}
	if _, ok := raw["message"]; raw != nil && !ok {
		return fmt.Errorf("field message in Alert: required")
	}
	if _, ok := raw["offset"]; raw != nil && !ok {
		return fmt.Errorf("field offset in Alert: required")
	}
	if _, ok := raw["period"]; raw != nil && !ok {
		return fmt.Errorf("field period in Alert: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in Alert: required")
	}
	if _, ok := raw["team_id"]; raw != nil && !ok {
		return fmt.Errorf("field team_id in Alert: required")
	}
	if _, ok := raw["threshold"]; raw != nil && !ok {
		return fmt.Errorf("field threshold in Alert: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Alert: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in Alert: required")
	}
	if _, ok := raw["window_s"]; raw != nil && !ok {
		return fmt.Errorf("field window_s in Alert: required")
	}
	type Plain Alert
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ID)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if 0 >= plain.WindowS {
		return fmt.Errorf("field %s: must be > %v", "window_s", 0)
	}
	*j = Alert(plain)
	return nil
}

// Stream position for non-event messages. On `reset`, consumers drop state and
// rebuild up to this position.
type FeedMarker struct {
	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS MatchClockSeconds `json:"match_clock_s"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID MatchID `json:"match_id"`

	// Offset corresponds to the JSON schema field "offset".
	Offset Offset `json:"offset"`

	// Period corresponds to the JSON schema field "period".
	Period Period `json:"period"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FeedMarker) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["match_clock_s"]; raw != nil && !ok {
		return fmt.Errorf("field match_clock_s in FeedMarker: required")
	}
	if _, ok := raw["match_id"]; raw != nil && !ok {
		return fmt.Errorf("field match_id in FeedMarker: required")
	}
	if _, ok := raw["offset"]; raw != nil && !ok {
		return fmt.Errorf("field offset in FeedMarker: required")
	}
	if _, ok := raw["period"]; raw != nil && !ok {
		return fmt.Errorf("field period in FeedMarker: required")
	}
	type Plain FeedMarker
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FeedMarker(plain)
	return nil
}

// One WebSocket message on the simulator feed. `kind` says which payload field is
// set.
type FeedMessage struct {
	// Event corresponds to the JSON schema field "event".
	Event *MatchEvent `json:"event,omitempty,omitzero"`

	// Kind corresponds to the JSON schema field "kind".
	Kind FeedMessageKind `json:"kind"`

	// Stream position for non-event messages. On `reset`, consumers drop state and
	// rebuild up to this position.
	Marker *FeedMarker `json:"marker,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`
}

type FeedMessageKind string

const FeedMessageKindEvent FeedMessageKind = "event"
const FeedMessageKindMatchEnd FeedMessageKind = "match_end"
const FeedMessageKindMatchStart FeedMessageKind = "match_start"
const FeedMessageKindReset FeedMessageKind = "reset"

var enumValues_FeedMessageKind = []interface{}{
	"event",
	"match_start",
	"reset",
	"match_end",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FeedMessageKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FeedMessageKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FeedMessageKind, v)
	}
	*j = FeedMessageKind(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FeedMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in FeedMessage: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in FeedMessage: required")
	}
	type Plain FeedMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FeedMessage(plain)
	return nil
}

// Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap
// across periods because of stoppage time, so always pair with period.
type MatchClockSeconds float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchClockSeconds) UnmarshalJSON(value []byte) error {
	type Plain MatchClockSeconds
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = MatchClockSeconds(plain)
	return nil
}

// A single normalized match event. Raw provider data never crosses the simulator
// boundary.
type MatchEvent struct {
	// EndLocation corresponds to the JSON schema field "end_location".
	EndLocation Point `json:"end_location,omitempty,omitzero"`

	// Stable unique event id (used for de-duplication).
	ID string `json:"id"`

	// Location corresponds to the JSON schema field "location".
	Location Point `json:"location,omitempty,omitzero"`

	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS MatchClockSeconds `json:"match_clock_s"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID MatchID `json:"match_id"`

	// Offset corresponds to the JSON schema field "offset".
	Offset Offset `json:"offset"`

	// Success or failure for actions that have one (e.g. pass completion). Omitted
	// otherwise.
	Outcome *MatchEventOutcome `json:"outcome,omitempty,omitzero"`

	// Period corresponds to the JSON schema field "period".
	Period Period `json:"period"`

	// Player corresponds to the JSON schema field "player".
	Player *Player `json:"player,omitempty,omitzero"`

	// Possession sequence number within the match.
	PossessionID int `json:"possession_id"`

	// PossessionTeamID corresponds to the JSON schema field "possession_team_id".
	PossessionTeamID int `json:"possession_team_id"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`

	// Shot corresponds to the JSON schema field "shot".
	Shot *ShotDetail `json:"shot,omitempty,omitzero"`

	// Team corresponds to the JSON schema field "team".
	Team Team `json:"team"`

	// Type corresponds to the JSON schema field "type".
	Type MatchEventType `json:"type"`
}

type MatchEventOutcome string

const MatchEventOutcomeFailure MatchEventOutcome = "failure"
const MatchEventOutcomeSuccess MatchEventOutcome = "success"

var enumValues_MatchEventOutcome = []interface{}{
	"success",
	"failure",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchEventOutcome) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MatchEventOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MatchEventOutcome, v)
	}
	*j = MatchEventOutcome(v)
	return nil
}

type MatchEventShotOutcome string

const MatchEventShotOutcomeBlocked MatchEventShotOutcome = "blocked"
const MatchEventShotOutcomeGoal MatchEventShotOutcome = "goal"
const MatchEventShotOutcomeOffTarget MatchEventShotOutcome = "off_target"
const MatchEventShotOutcomeOther MatchEventShotOutcome = "other"
const MatchEventShotOutcomePost MatchEventShotOutcome = "post"
const MatchEventShotOutcomeSaved MatchEventShotOutcome = "saved"

var enumValues_MatchEventShotOutcome = []interface{}{
	"goal",
	"saved",
	"blocked",
	"off_target",
	"post",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchEventShotOutcome) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MatchEventShotOutcome {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MatchEventShotOutcome, v)
	}
	*j = MatchEventShotOutcome(v)
	return nil
}

type MatchEventType string

const MatchEventTypeBallReceipt MatchEventType = "ball_receipt"
const MatchEventTypeBallRecovery MatchEventType = "ball_recovery"
const MatchEventTypeBlock MatchEventType = "block"
const MatchEventTypeCarry MatchEventType = "carry"
const MatchEventTypeClearance MatchEventType = "clearance"
const MatchEventTypeDispossessed MatchEventType = "dispossessed"
const MatchEventTypeDribble MatchEventType = "dribble"
const MatchEventTypeDribbledPast MatchEventType = "dribbled_past"
const MatchEventTypeDuel MatchEventType = "duel"
const MatchEventTypeFiftyFifty MatchEventType = "fifty_fifty"
const MatchEventTypeFoulCommitted MatchEventType = "foul_committed"
const MatchEventTypeFoulWon MatchEventType = "foul_won"
const MatchEventTypeGoalkeeper MatchEventType = "goalkeeper"
const MatchEventTypeHalfEnd MatchEventType = "half_end"
const MatchEventTypeHalfStart MatchEventType = "half_start"
const MatchEventTypeInterception MatchEventType = "interception"
const MatchEventTypeMiscontrol MatchEventType = "miscontrol"
const MatchEventTypeOffside MatchEventType = "offside"
const MatchEventTypeOther MatchEventType = "other"
const MatchEventTypePass MatchEventType = "pass"
const MatchEventTypePressure MatchEventType = "pressure"
const MatchEventTypeShot MatchEventType = "shot"
const MatchEventTypeSubstitution MatchEventType = "substitution"

var enumValues_MatchEventType = []interface{}{
	"pass",
	"carry",
	"shot",
	"ball_receipt",
	"ball_recovery",
	"interception",
	"duel",
	"dribble",
	"dribbled_past",
	"clearance",
	"block",
	"pressure",
	"foul_committed",
	"foul_won",
	"miscontrol",
	"dispossessed",
	"goalkeeper",
	"fifty_fifty",
	"offside",
	"substitution",
	"half_start",
	"half_end",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchEventType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MatchEventType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MatchEventType, v)
	}
	*j = MatchEventType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in MatchEvent: required")
	}
	if _, ok := raw["match_clock_s"]; raw != nil && !ok {
		return fmt.Errorf("field match_clock_s in MatchEvent: required")
	}
	if _, ok := raw["match_id"]; raw != nil && !ok {
		return fmt.Errorf("field match_id in MatchEvent: required")
	}
	if _, ok := raw["offset"]; raw != nil && !ok {
		return fmt.Errorf("field offset in MatchEvent: required")
	}
	if _, ok := raw["period"]; raw != nil && !ok {
		return fmt.Errorf("field period in MatchEvent: required")
	}
	if _, ok := raw["possession_id"]; raw != nil && !ok {
		return fmt.Errorf("field possession_id in MatchEvent: required")
	}
	if _, ok := raw["possession_team_id"]; raw != nil && !ok {
		return fmt.Errorf("field possession_team_id in MatchEvent: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in MatchEvent: required")
	}
	if _, ok := raw["team"]; raw != nil && !ok {
		return fmt.Errorf("field team in MatchEvent: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in MatchEvent: required")
	}
	type Plain MatchEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.ID)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if 0 > plain.PossessionID {
		return fmt.Errorf("field %s: must be >= %v", "possession_id", 0)
	}
	*j = MatchEvent(plain)
	return nil
}

type MatchID int

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchID) UnmarshalJSON(value []byte) error {
	type Plain MatchID
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = MatchID(plain)
	return nil
}

// A match without its events.
type MatchInfo struct {
	// AwayScore corresponds to the JSON schema field "away_score".
	AwayScore int `json:"away_score"`

	// AwayTeam corresponds to the JSON schema field "away_team".
	AwayTeam Team `json:"away_team"`

	// Competition corresponds to the JSON schema field "competition".
	Competition string `json:"competition"`

	// Kick-off date, YYYY-MM-DD.
	Date string `json:"date"`

	// HomeScore corresponds to the JSON schema field "home_score".
	HomeScore int `json:"home_score"`

	// HomeTeam corresponds to the JSON schema field "home_team".
	HomeTeam Team `json:"home_team"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID MatchID `json:"match_id"`

	// Season corresponds to the JSON schema field "season".
	Season string `json:"season"`

	// Stage corresponds to the JSON schema field "stage".
	Stage string `json:"stage"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["away_score"]; raw != nil && !ok {
		return fmt.Errorf("field away_score in MatchInfo: required")
	}
	if _, ok := raw["away_team"]; raw != nil && !ok {
		return fmt.Errorf("field away_team in MatchInfo: required")
	}
	if _, ok := raw["competition"]; raw != nil && !ok {
		return fmt.Errorf("field competition in MatchInfo: required")
	}
	if _, ok := raw["date"]; raw != nil && !ok {
		return fmt.Errorf("field date in MatchInfo: required")
	}
	if _, ok := raw["home_score"]; raw != nil && !ok {
		return fmt.Errorf("field home_score in MatchInfo: required")
	}
	if _, ok := raw["home_team"]; raw != nil && !ok {
		return fmt.Errorf("field home_team in MatchInfo: required")
	}
	if _, ok := raw["match_id"]; raw != nil && !ok {
		return fmt.Errorf("field match_id in MatchInfo: required")
	}
	if _, ok := raw["season"]; raw != nil && !ok {
		return fmt.Errorf("field season in MatchInfo: required")
	}
	if _, ok := raw["stage"]; raw != nil && !ok {
		return fmt.Errorf("field stage in MatchInfo: required")
	}
	type Plain MatchInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.AwayScore {
		return fmt.Errorf("field %s: must be >= %v", "away_score", 0)
	}
	if matched, _ := regexp.MatchString(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`, string(plain.Date)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Date", `^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	}
	if 0 > plain.HomeScore {
		return fmt.Errorf("field %s: must be >= %v", "home_score", 0)
	}
	*j = MatchInfo(plain)
	return nil
}

// Matches the simulator can replay (GET /matches).
type MatchList struct {
	// Matches corresponds to the JSON schema field "matches".
	Matches []MatchInfo `json:"matches"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MatchList) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["matches"]; raw != nil && !ok {
		return fmt.Errorf("field matches in MatchList: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in MatchList: required")
	}
	type Plain MatchList
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = MatchList(plain)
	return nil
}

// Rolling-window metrics for both teams at a point in match time.
type MetricSnapshot struct {
	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS MatchClockSeconds `json:"match_clock_s"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID MatchID `json:"match_id"`

	// Offset of the last event included.
	Offset Offset `json:"offset"`

	// Period corresponds to the JSON schema field "period".
	Period Period `json:"period"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`

	// Teams corresponds to the JSON schema field "teams".
	Teams []TeamMetrics `json:"teams"`

	// Window length in match seconds (e.g. 300 or 600).
	WindowS int `json:"window_s"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MetricSnapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["match_clock_s"]; raw != nil && !ok {
		return fmt.Errorf("field match_clock_s in MetricSnapshot: required")
	}
	if _, ok := raw["match_id"]; raw != nil && !ok {
		return fmt.Errorf("field match_id in MetricSnapshot: required")
	}
	if _, ok := raw["offset"]; raw != nil && !ok {
		return fmt.Errorf("field offset in MetricSnapshot: required")
	}
	if _, ok := raw["period"]; raw != nil && !ok {
		return fmt.Errorf("field period in MetricSnapshot: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in MetricSnapshot: required")
	}
	if _, ok := raw["teams"]; raw != nil && !ok {
		return fmt.Errorf("field teams in MetricSnapshot: required")
	}
	if _, ok := raw["window_s"]; raw != nil && !ok {
		return fmt.Errorf("field window_s in MetricSnapshot: required")
	}
	type Plain MetricSnapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Teams != nil && len(plain.Teams) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "teams", 2)
	}
	if len(plain.Teams) > 2 {
		return fmt.Errorf("field %s length: must be <= %d", "teams", 2)
	}
	if 0 >= plain.WindowS {
		return fmt.Errorf("field %s: must be > %v", "window_s", 0)
	}
	*j = MetricSnapshot(plain)
	return nil
}

// Per-match sequence number of an event in the feed, starting at 0.
type Offset int

// UnmarshalJSON implements json.Unmarshaler.
func (j *Offset) UnmarshalJSON(value []byte) error {
	type Plain Offset
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 0)
	}
	*j = Offset(plain)
	return nil
}

// 1-2 regular halves, 3-4 extra time, 5 penalty shootout.
type Period int

// UnmarshalJSON implements json.Unmarshaler.
func (j *Period) UnmarshalJSON(value []byte) error {
	type Plain Period
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 5 < plain {
		return fmt.Errorf("field %s: must be <= %v", "", 5)
	}
	if 1 > plain {
		return fmt.Errorf("field %s: must be >= %v", "", 1)
	}
	*j = Period(plain)
	return nil
}

// Request body for the simulator's HTTP control API.
type PlaybackCommand struct {
	// Command corresponds to the JSON schema field "command".
	Command PlaybackCommandCommand `json:"command"`

	// Required for load_match.
	MatchID *MatchID `json:"match_id,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`

	// Required for seek.
	SeekTo *SeekTarget `json:"seek_to,omitempty,omitzero"`

	// Playback speed multiplier. Required for set_speed.
	Speed *float64 `json:"speed,omitempty,omitzero"`
}

type PlaybackCommandCommand string

const PlaybackCommandCommandLoadMatch PlaybackCommandCommand = "load_match"
const PlaybackCommandCommandPause PlaybackCommandCommand = "pause"
const PlaybackCommandCommandPlay PlaybackCommandCommand = "play"
const PlaybackCommandCommandSeek PlaybackCommandCommand = "seek"
const PlaybackCommandCommandSetSpeed PlaybackCommandCommand = "set_speed"

var enumValues_PlaybackCommandCommand = []interface{}{
	"load_match",
	"play",
	"pause",
	"set_speed",
	"seek",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PlaybackCommandCommand) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PlaybackCommandCommand {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PlaybackCommandCommand, v)
	}
	*j = PlaybackCommandCommand(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PlaybackCommand) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["command"]; raw != nil && !ok {
		return fmt.Errorf("field command in PlaybackCommand: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in PlaybackCommand: required")
	}
	type Plain PlaybackCommand
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Speed != nil && 1000 < *plain.Speed {
		return fmt.Errorf("field %s: must be <= %v", "speed", 1000)
	}
	if plain.Speed != nil && 0 >= *plain.Speed {
		return fmt.Errorf("field %s: must be > %v", "speed", 0)
	}
	*j = PlaybackCommand(plain)
	return nil
}

// Current simulator playback state.
type PlaybackStatus struct {
	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS *MatchClockSeconds `json:"match_clock_s,omitempty,omitzero"`

	// MatchID corresponds to the JSON schema field "match_id".
	MatchID *MatchID `json:"match_id,omitempty,omitzero"`

	// Next offset to be emitted.
	Offset *Offset `json:"offset,omitempty,omitzero"`

	// Period corresponds to the JSON schema field "period".
	Period *Period `json:"period,omitempty,omitzero"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion SchemaVersion `json:"schema_version"`

	// Speed corresponds to the JSON schema field "speed".
	Speed float64 `json:"speed"`

	// State corresponds to the JSON schema field "state".
	State PlaybackStatusState `json:"state"`
}

type PlaybackStatusState string

const PlaybackStatusStateEnded PlaybackStatusState = "ended"
const PlaybackStatusStateIdle PlaybackStatusState = "idle"
const PlaybackStatusStatePaused PlaybackStatusState = "paused"
const PlaybackStatusStatePlaying PlaybackStatusState = "playing"

var enumValues_PlaybackStatusState = []interface{}{
	"idle",
	"playing",
	"paused",
	"ended",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PlaybackStatusState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_PlaybackStatusState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_PlaybackStatusState, v)
	}
	*j = PlaybackStatusState(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PlaybackStatus) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in PlaybackStatus: required")
	}
	if _, ok := raw["speed"]; raw != nil && !ok {
		return fmt.Errorf("field speed in PlaybackStatus: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in PlaybackStatus: required")
	}
	type Plain PlaybackStatus
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain.Speed {
		return fmt.Errorf("field %s: must be > %v", "speed", 0)
	}
	*j = PlaybackStatus(plain)
	return nil
}

type Player struct {
	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Player) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Player: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Player: required")
	}
	type Plain Player
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Player(plain)
	return nil
}

// Pitch coordinates [x, y] on a 120x80 pitch, oriented so the acting team attacks
// towards x = 120.
type Point []float64

// Wire-format version. Bump only for breaking changes.
type SchemaVersion int

// UnmarshalJSON implements json.Unmarshaler.
func (j *SchemaVersion) UnmarshalJSON(value []byte) error {
	type Plain SchemaVersion
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "", 1)
	}
	*j = SchemaVersion(plain)
	return nil
}

// Required for seek.
type SeekTarget struct {
	// MatchClockS corresponds to the JSON schema field "match_clock_s".
	MatchClockS MatchClockSeconds `json:"match_clock_s"`

	// Period corresponds to the JSON schema field "period".
	Period Period `json:"period"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SeekTarget) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["match_clock_s"]; raw != nil && !ok {
		return fmt.Errorf("field match_clock_s in SeekTarget: required")
	}
	if _, ok := raw["period"]; raw != nil && !ok {
		return fmt.Errorf("field period in SeekTarget: required")
	}
	type Plain SeekTarget
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SeekTarget(plain)
	return nil
}

type ShotDetail struct {
	// Outcome corresponds to the JSON schema field "outcome".
	Outcome MatchEventShotOutcome `json:"outcome"`

	// XG corresponds to the JSON schema field "xg".
	XG float64 `json:"xg"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ShotDetail) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["outcome"]; raw != nil && !ok {
		return fmt.Errorf("field outcome in ShotDetail: required")
	}
	if _, ok := raw["xg"]; raw != nil && !ok {
		return fmt.Errorf("field xg in ShotDetail: required")
	}
	type Plain ShotDetail
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.XG {
		return fmt.Errorf("field %s: must be <= %v", "xg", 1)
	}
	if 0 > plain.XG {
		return fmt.Errorf("field %s: must be >= %v", "xg", 0)
	}
	*j = ShotDetail(plain)
	return nil
}

type Team struct {
	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type TeamMetrics struct {
	// Share of attacking-third touches in the window (0-1).
	FieldTilt float64 `json:"field_tilt"`

	// PressureIndex corresponds to the JSON schema field "pressure_index".
	PressureIndex float64 `json:"pressure_index"`

	// TeamID corresponds to the JSON schema field "team_id".
	TeamID int `json:"team_id"`

	// XtAdded corresponds to the JSON schema field "xt_added".
	XtAdded float64 `json:"xt_added"`

	// xT added per match minute.
	XtVelocity float64 `json:"xt_velocity"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TeamMetrics) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["field_tilt"]; raw != nil && !ok {
		return fmt.Errorf("field field_tilt in TeamMetrics: required")
	}
	if _, ok := raw["pressure_index"]; raw != nil && !ok {
		return fmt.Errorf("field pressure_index in TeamMetrics: required")
	}
	if _, ok := raw["team_id"]; raw != nil && !ok {
		return fmt.Errorf("field team_id in TeamMetrics: required")
	}
	if _, ok := raw["xt_added"]; raw != nil && !ok {
		return fmt.Errorf("field xt_added in TeamMetrics: required")
	}
	if _, ok := raw["xt_velocity"]; raw != nil && !ok {
		return fmt.Errorf("field xt_velocity in TeamMetrics: required")
	}
	type Plain TeamMetrics
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.FieldTilt {
		return fmt.Errorf("field %s: must be <= %v", "field_tilt", 1)
	}
	if 0 > plain.FieldTilt {
		return fmt.Errorf("field %s: must be >= %v", "field_tilt", 0)
	}
	if 0 > plain.PressureIndex {
		return fmt.Errorf("field %s: must be >= %v", "pressure_index", 0)
	}
	*j = TeamMetrics(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Team) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Team: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Team: required")
	}
	type Plain Team
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Team(plain)
	return nil
}
