# generated by datamodel-codegen:
#   filename:  alert.schema.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated, Literal
from pydantic import BaseModel, Field


class AlertType(StrEnum):
    momentum_shift = "momentum_shift"
    goal_threat = "goal_threat"
    control_shift = "control_shift"


class Alert(BaseModel):
    """
    A tactical alert raised by a detector.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    id: Annotated[str, Field(min_length=1)]
    match_id: Annotated[int, Field(ge=0)]
    offset: Annotated[int, Field(description="Offset of the event that triggered the alert.", ge=0)]
    period: Annotated[
        int,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ]
    match_clock_s: Annotated[
        float,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ]
    type: Annotated[AlertType, Field(title="AlertType")]
    team_id: int
    value: Annotated[
        float, Field(description="Detector output (e.g. z-score or heuristic goal score).")
    ]
    threshold: float
    window_s: Annotated[int, Field(gt=0)]
    features: Annotated[
        dict[str, float], Field(description="Inputs that contributed to the alert, by name.")
    ]
    message: str
