# generated by datamodel-codegen:
#   filename:  command.schema.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, Field
from typing import Annotated, Literal


class PlaybackCommandType(StrEnum):
    load_match = "load_match"
    play = "play"
    pause = "pause"
    set_speed = "set_speed"
    seek = "seek"


class SeekTarget(BaseModel):
    """
    Required for seek.
    """

    period: Annotated[
        int,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ]
    match_clock_s: Annotated[
        float,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ]


class PlaybackCommand(BaseModel):
    """
    Request body for the simulator's HTTP control API.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    command: Annotated[PlaybackCommandType, Field(title="PlaybackCommandType")]
    match_id: Annotated[int | None, Field(description="Required for load_match.", ge=0)] = None
    speed: Annotated[
        float | None,
        Field(description="Playback speed multiplier. Required for set_speed.", gt=0.0, le=1000.0),
    ] = None
    seek_to: Annotated[
        SeekTarget | None, Field(description="Required for seek.", title="SeekTarget")
    ] = None
