# generated by datamodel-codegen:
#   filename:  common.schema.json

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, Field, RootModel


class Common(RootModel[Any]):
    root: Annotated[
        Any,
        Field(description="Shared definitions referenced by the other schemas.", title="Common"),
    ]


class Team(BaseModel):
    id: int
    name: str


class Player(BaseModel):
    id: int
    name: str
