# generated by datamodel-codegen:
#   filename:  event.schema.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated, Literal
from pydantic import BaseModel, Field
from . import common_schema


class EventType(StrEnum):
    pass_ = "pass"
    carry = "carry"
    shot = "shot"
    ball_receipt = "ball_receipt"
    ball_recovery = "ball_recovery"
    interception = "interception"
    duel = "duel"
    dribble = "dribble"
    dribbled_past = "dribbled_past"
    clearance = "clearance"
    block = "block"
    pressure = "pressure"
    foul_committed = "foul_committed"
    foul_won = "foul_won"
    miscontrol = "miscontrol"
    dispossessed = "dispossessed"
    goalkeeper = "goalkeeper"
    fifty_fifty = "fifty_fifty"
    offside = "offside"
    substitution = "substitution"
    half_start = "half_start"
    half_end = "half_end"
    other = "other"


class EventOutcome(StrEnum):
    """
    Success or failure for actions that have one (e.g. pass completion). Omitted otherwise.
    """

    success = "success"
    failure = "failure"


class ShotOutcome(StrEnum):
    goal = "goal"
    saved = "saved"
    blocked = "blocked"
    off_target = "off_target"
    post = "post"
    other = "other"


class ShotDetail(BaseModel):
    xg: Annotated[float, Field(ge=0.0, le=1.0)]
    outcome: Annotated[ShotOutcome, Field(title="ShotOutcome")]


class MatchEvent(BaseModel):
    """
    A single normalized match event. Raw provider data never crosses the simulator boundary.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    id: Annotated[
        str, Field(description="Stable unique event id (used for de-duplication).", min_length=1)
    ]
    match_id: Annotated[int, Field(ge=0)]
    offset: Annotated[
        int,
        Field(
            description="Per-match sequence number of an event in the feed, starting at 0.", ge=0
        ),
    ]
    period: Annotated[
        int,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ]
    match_clock_s: Annotated[
        float,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ]
    type: Annotated[EventType, Field(title="EventType")]
    team: common_schema.Team
    possession_id: Annotated[
        int, Field(description="Possession sequence number within the match.", ge=0)
    ]
    possession_team_id: int
    player: common_schema.Player | None = None
    location: Annotated[
        list[float] | None,
        Field(
            description="Pitch coordinates [x, y] on a 120x80 pitch, oriented so the acting team attacks towards x = 120.",
            max_length=2,
            min_length=2,
        ),
    ] = None
    end_location: Annotated[
        list[float] | None,
        Field(
            description="Pitch coordinates [x, y] on a 120x80 pitch, oriented so the acting team attacks towards x = 120.",
            max_length=2,
            min_length=2,
        ),
    ] = None
    outcome: Annotated[
        EventOutcome | None,
        Field(
            description="Success or failure for actions that have one (e.g. pass completion). Omitted otherwise.",
            title="EventOutcome",
        ),
    ] = None
    shot: Annotated[ShotDetail | None, Field(title="ShotDetail")] = None
