# generated by datamodel-codegen:
#   filename:  feed.schema.json

from __future__ import annotations
from enum import StrEnum
from pydantic import BaseModel, Field
from . import event_schema
from typing import Annotated, Literal


class FeedMessageKind(StrEnum):
    event = "event"
    match_start = "match_start"
    reset = "reset"
    match_end = "match_end"


class FeedMarker(BaseModel):
    """
    Stream position for non-event messages. On `reset`, consumers drop state and rebuild up to this position.
    """

    match_id: Annotated[int, Field(ge=0)]
    offset: Annotated[
        int,
        Field(
            description="Per-match sequence number of an event in the feed, starting at 0.", ge=0
        ),
    ]
    period: Annotated[
        int,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ]
    match_clock_s: Annotated[
        float,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ]


class FeedMessage(BaseModel):
    """
    One WebSocket message on the simulator feed. `kind` says which payload field is set.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    kind: Annotated[FeedMessageKind, Field(title="FeedMessageKind")]
    event: event_schema.MatchEvent | None = None
    marker: Annotated[
        FeedMarker | None,
        Field(
            description="Stream position for non-event messages. On `reset`, consumers drop state and rebuild up to this position.",
            title="FeedMarker",
        ),
    ] = None
