# generated by datamodel-codegen:
#   filename:  match_list.schema.json

from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, Field
from . import common_schema


class MatchInfo(BaseModel):
    """
    A match without its events.
    """

    match_id: Annotated[int, Field(ge=0)]
    competition: str
    season: str
    stage: str
    date: Annotated[
        str, Field(description="Kick-off date, YYYY-MM-DD.", pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}$")
    ]
    home_team: common_schema.Team
    away_team: common_schema.Team
    home_score: Annotated[int, Field(ge=0)]
    away_score: Annotated[int, Field(ge=0)]


class MatchList(BaseModel):
    """
    Matches the simulator can replay (GET /matches).
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    matches: list[MatchInfo]
