# generated by datamodel-codegen:
#   filename:  metric.schema.json

from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, Field


class TeamMetrics(BaseModel):
    team_id: int
    field_tilt: Annotated[
        float,
        Field(description="Share of attacking-third touches in the window (0-1).", ge=0.0, le=1.0),
    ]
    xt_added: float
    xt_velocity: Annotated[float, Field(description="xT added per match minute.")]
    pressure_index: Annotated[float, Field(ge=0.0)]


class MetricSnapshot(BaseModel):
    """
    Rolling-window metrics for both teams at a point in match time.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    match_id: Annotated[int, Field(ge=0)]
    offset: Annotated[int, Field(description="Offset of the last event included.", ge=0)]
    period: Annotated[
        int,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ]
    match_clock_s: Annotated[
        float,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ]
    window_s: Annotated[
        int, Field(description="Window length in match seconds (e.g. 300 or 600).", gt=0)
    ]
    teams: Annotated[list[TeamMetrics], Field(max_length=2, min_length=2)]
