# generated by datamodel-codegen:
#   filename:  status.schema.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated, Literal
from pydantic import BaseModel, Field


class PlaybackState(StrEnum):
    idle = "idle"
    playing = "playing"
    paused = "paused"
    ended = "ended"


class PlaybackStatus(BaseModel):
    """
    Current simulator playback state.
    """

    schema_version: Annotated[
        Literal[1], Field(description="Wire-format version. Bump only for breaking changes.")
    ]
    state: Annotated[PlaybackState, Field(title="PlaybackState")]
    speed: Annotated[float, Field(gt=0.0)]
    match_id: Annotated[int | None, Field(ge=0)] = None
    offset: Annotated[int | None, Field(description="Next offset to be emitted.", ge=0)] = None
    period: Annotated[
        int | None,
        Field(description="1-2 regular halves, 3-4 extra time, 5 penalty shootout.", ge=1, le=5),
    ] = None
    match_clock_s: Annotated[
        float | None,
        Field(
            description="Game clock in seconds (e.g. the second half starts at 2700). Clocks overlap across periods because of stoppage time, so always pair with period.",
            ge=0.0,
        ),
    ] = None
